### ISSUE TITLE
TODO extracting doesn't work

### ISSUE THREAD

**Issue by pierregoudjo** [robcowie/SublimeTODO#13]
When I want to show TODO results, blank page appears.
The console tracback is:

```
Traceback (most recent call last):
   File "./todo.py", line 265, in render
   File "./todo.py", line 234, in render_to_view
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 104: ordinal not in range(128)
```

**Comment by robcowie** [comment]
What version are you using? Latest should be listed as `v2012.01.21.17.16.06` (via the List Installed Packages command)

Early versions did not handle encoding issues like this. I reckon I've 'fixed' it. I can't always correctly decode the file contents as the plugin doesn't know what encoding is used in the file. It tries utf8, then the configured default encoding (ST2 setting) and fails silently if it still can't decode.

I'll take a look at the code anyway.

**Comment by pierregoudjo** [comment]
I am using v2012.01.21.17.16.06 version of the plugin.

**Comment by robcowie** [comment]
What is your default file encoding and fallback encoding (see `File Settings - Default`).

I'm having a hard time reproducing the problem. It would be great if you could isolate the file that is causing the problem and share it (or the part of it that is the issue).

**Comment by pierregoudjo** [comment]
My default file encoding is UTF-8, fallback encoding is "Western (Windows 1252)". I am working on Ubuntu Linux 11.10. Do you think that my problem come from my OS?

**Comment by robcowie** [comment]
Unlikely to be an OS issue. It is inevitably a bug of my making. Any luck isolating the offending file?

**Comment by pierregoudjo** [comment]
I have a look to the file (despite Python isn't my stuff) and your todo.py looks good. I can't locate the bug.

**Comment by robcowie** [comment]
Are you still having issues? Does the plugin run on _any_ of your files?

**Comment by pierregoudjo** [comment]
Issues still persist. I ran the plugin on php, js, txt. Nothing

**Comment by robcowie** [comment]
@pierregoudjo Just merged a pull request from @kch42 that should fix your issue. Can you update and let me (us) know if the your issue persists. Thanks.

**Comment by pierregoudjo** [comment]
The plugin works now. Great! Thanks you!
