### ISSUE TITLE
How do add custom patterns?

### ISSUE THREAD

**Issue by Tolmark12** [robcowie/SublimeTODO#14]
I'm probably just missing something, but I've been trying to add a custom pattern to my user settings file, do you have a sample of what that looks like in json syntax?

This is what I've tried:

``` javascript
"patterns": {
    "BUG": "r'BUG[\\s]*?:+(?P<todo>.*)$'"
}
```

**Comment by robcowie** [comment]
In your user settings file, add a new item `"todo": {}`. Add patterns to that object. It should look like:

``` javascript
{
    //other, existing settings...

    "todo": {
        "patterns": {
            "BUG": "BUG[\\s]*?:+(?P<bug>.*)$"
        }
    }
}
```

Have a look at my user settings at https://gist.github.com/1719536

**Comment by Tolmark12** [comment]
Perfect, thanks!
