### ISSUE TITLE
To do overview - link to file

### ISSUE THREAD

**Issue by anthonyringoet** [robcowie/SublimeTODO#20]
I'm just wondering if it's possible to enable a link behaviour from the to do overview page to the specific file and line number.
Now I get an overview, but it would be pretty handy if I could click and open the right file.

**Comment by robcowie** [comment]
`alt-double click` on a line and it'll jump to the message file and line.

I pushed this feature about a week ago and several people have said that the package has not been updated by the package manager. I have yet to get to the bottom of it. Please remove the package (via the package manager) and reinstall.

**Comment by anthonyringoet** [comment]
Awesome, It's working now. Thanks!
