### ISSUE TITLE
Mapping keys in windows

### ISSUE THREAD

**Issue by erinata** [robcowie/SublimeTODO#21]
This plugin is excellent!!!!

It seems that you didn't map the keys for task navigation in windows.  I copied the keymaps of OSX and it seems that it works properly. If you don't mind please include it in your plugin so the Windows people can also navigate in the beautifully generated Todo list?

https://gist.github.com/2176513 

In this file, I also maps the "up" and "down" key in addition to the default "n" and "p". I think it makes sense to use arrow keys to navigate?

Another problem is that if I type something (say [  ] or { } or if I hit backspace) in the todo list view, it messes up the list and I cannot navigate property. I guess you need to disable those keys (or make the whole document read only) in the todo list view?

**Comment by robcowie** [comment]
Cheers for your efforts; I'll certainly include the windows keymap. The todo list _should_ be read-only already. I'll look into it.

**Comment by robcowie** [comment]
See e1dc9f8e67

**Comment by erinata** [comment]
Looks like you don't like the up and down keymapping.........I will add it to my own branch then.

**Comment by robcowie** [comment]
Ha. Nope, I just forgot. I'll add them shortly

**Comment by robcowie** [comment]
Up/down added. See 8463fa1d43. Appreciate some testing on windows if you have the time.

**Comment by erinata** [comment]
It works perfectly. I also test it in linux.
