### ISSUE TITLE
scan open files only

### ISSUE THREAD

**Issue by chrisjaure** [robcowie/SublimeTODO#22]
I'd love to use this plugin, but we have a rather large project with thousands of files and scanning them all can take a bit. An option to scan only open files would be awesome.

**Comment by robcowie** [comment]
Sounds like a useful feature, I'll have a think about it. Would you prefer a setting (say `open_files_only: True`) or a second command ('Show TODOs in open files only`)?

Also, If you have the time I'd appreciate some numbers about the speed of the plugin when scanning large numbers of files. I've been considering changing the way the plugin works... scanning once in the background, maintaining a list of messages and updating it on file change. Could improve performance but it's a lot of work and I'm not sure it's worth the effort.

**Comment by chrisjaure** [comment]
It takes ~1:40 to scan ~4200 files.

I'd prefer a second command. And for consistent formatting with other commands, it should probably be something like "TODO: Open Files" but I know there's other todo plugins you need to avoid naming conflicts with.

**Comment by robcowie** [comment]
Damn it... I just pushed a commit I didn't want to push. Please ignore that; I'll revert.

**Comment by robcowie** [comment]
Second command `Show TODOs: Open files only` added. Give it a shot and let me know if there are any issues.

**Comment by chrisjaure** [comment]
Works perfectly. Thanks :)

**Comment by robcowie** [comment]
:+1:
