### ISSUE TITLE
UnboundLocalError in extract(self)

### ISSUE THREAD

**Issue by Tyderion** [robcowie/SublimeTODO#37]
Hi there

I don't know why i get this error. I started a new rails project a while ago and now your plugin produces an UnboundLocalError when I try to view all TODOs.
 In a different project my SublimeTODO-config works perfect, so I don't think my configuration is part of the error.
This gist contains the traceback and a very simple fix:
https://gist.github.com/4080313

**Comment by robcowie** [comment]
Thanks dude. The fix is committed and I'll push an update to Sublime packages shortly

**Comment by Tyderion** [comment]
thanks for fixing :+1:
