### ISSUE TITLE
Open the file when double clicking

### ISSUE THREAD

**Issue by jcldavid** [robcowie/SublimeTODO#39]
You can see this feature when you search for texts in files inside ST2, when you double click on the excerpt of that file, that files gets opened on a new tab on that specific line where it's found. Would it be possible to grab that specific functionality for SublimeTODO?

**Comment by Hezix** [comment]
I Second that this feature would be very useful.

**Comment by fnkr** [comment]
+1 from me.

**Comment by robcowie** [comment]
It sort of exists; If you hold `alt` (or `shift` if on linux) and double-click, it will open the appropriate line.

It's currently hard to find the time to hack on the plugin right now and there are several things that need doing to make it easier to maintain (not least, make it py3 compatible). I'll see what I can do.

**Comment by fnkr** [comment]
Thanks, working perfect!

**Comment by Hezix** [comment]
Tested the alt+double click, works great.  Thanks.

**Comment by justinclayton** [comment]
Very handy; I would argue that if this feature is more prominently documented (perhaps in the README), you could probably even close this issue to most people's satisfaction.

**Comment by jcldavid** [comment]
Actually, it is in the README.

`alt-double click` (`shift-double click` in Linux)
