### ISSUE TITLE
Command to go to a to do item

### ISSUE THREAD

**Issue by kgrossjo** [robcowie/SublimeTODO#5]
In the list of to do items, it would be cool if I could jump to the current one with a keybinding.  This would open the correct file and move point to the correct line in that file.

**Comment by jimpriest** [comment]
Either a keybinding or being able to click on the filename / line # (similar to how search works) would be great!

**Comment by nigauw** [comment]
It would really help to display the path as well as the filename and line.

**Comment by hced** [comment]
+1 for this. Navigating to the todo/fix items would be the killer feature.

**Comment by zanematthew** [comment]
Yeah I would love this feature, with out it really I can really just use the native search feature in sublime2

**Comment by robcowie** [comment]
Closing this as it is closely related to #6

I have a dev version with keyboard navigation through the list; (n)ext, (p)revious, (c)lear selection. The selected item is highlighted though of course that depends on your theme.
Navigating to the file and line is somewhat tricky. Whatever the find in files results use, it isn't documented or obvious.

**Comment by kgrossjo** [comment]
Well, find in files is easy, you can do it with build systems.  Any line that starts with a non-whitespace and ends with colon contains a file name.  Subsequent lines that begin with whitespace, then contain a number, then a colon, that number will be the line number to go to.

This page explains how to (easily) have file name and line number on different lines:
http://sublimetext.info/docs/en/reference/build_systems.html

Kai
