### ISSUE TITLE
@todo pattern?

### ISSUE THREAD

**Issue by Tomzon** [robcowie/SublimeTODO#52]
Hi, I've tried everything, can't seem to figure out a pattern that would work with @todo Description (PHPDoc type comments).

Can someone help please? I would be most thankful :).

**Comment by Tomzon** [comment]
Anyone? It should be an easy fix. It's idiotic to change all @todo-s to TODO-s, just because of this :P

**Comment by vovkkk** [comment]
Try to put this into your 'Settings - User'

```
{
    "todo": {
        "patterns": {
            "@todo": "@todo[\\s]*?:?(?P<phptodo>\\S.*)$"
        },
        "case_sensitive": false
    }
}
```

`"case_sensitive": false` is not necessary I guess, but it seems more flexible than when it's true.

**Comment by chadhenry** [comment]
@Tomzon, this is what I have in my 'Settings - User':

<pre>
{
    "todo": {
        "case_sensitive": false,
        "core_patterns": {
            "@TODO": "@TODO[\\s:]+(?P<todo>.*)$",
            "@NOTE": "@NOTE[\\s:]+(?P<note>.*)$",
            "@FIXME": "@FIX ?ME[\\s:]+(?P<fixme>.*)$",
            "@CHANGED": "@CHANGED[\\s:]+(?P<changed>.*)$"
                },
        "patterns": {
            "@SOURCE": "@SOURCE[\\s:]*?:+(?P<source>.*)$"
        },
        "folder_exclude_patterns": [
            "inc"
        ]
    }
}
</pre>

It will return the following: @todo:, @todo, @TODO:, @TODO - notice capitalization and colons. This may, or may not be the best way to solve your problem but it works for me and I haven't seen any downsides to it yet.

**Comment by Tomzon** [comment]
Thank you both very much. I was waiting for 11 days and now you gave it in less than an hour. Both are working!

Cheers
