### ISSUE TITLE
file_exclude_patterns per project instead of global

### ISSUE THREAD

**Issue by nunoh** [robcowie/SublimeTODO#55]
I don't seem to be able to ignore files to look for TODO annotations per project, just globally. In the README, it is supposedly working. So, am I missing something or is it kind of a bug?

I have tried both these ways with no success:

```
{
    "todo": {
        "file_exclude_patterns": ["*.sty"]
    },

    "folders":
    [
        {
            "path": "/C/Users/Nuno/myproject",
        }
    ]
}
```

and:

```
{
    "folders":
    [
        {
            "path": "/C/Users/Nuno/myproject",
            "todo": {
                "file_exclude_patterns": ["*.sty"]
            }
        }
    ]
}
```

But it does work however, when I place it in the global user settings preferences files.

**Comment by vovkkk** [comment]
```
{
    "folders":
    [
        {
            "path": "/C/Users/Nuno/myproject"
        }
    ],
    "settings":
    {
        "todo": 
        {
            "file_exclude_patterns": ["*.sty"]
        }
    }
}
```

**Comment by nunoh** [comment]
That did the trick. Thanks! 

I would advise the author of the plugin though, to make it clearer in the README and possibly include the snippet in there too to make it easier for first-timers customizing sublime project settings.
