### ISSUE TITLE
Set tab title

### ISSUE THREAD

**Issue by kgrossjo** [robcowie/SublimeTODO#7]
I think the tab created by the "show todos" command should not be named "untitled".  It should be named "TO DO" or "ACTIONS" or maybe "\* TODO *".

**Comment by robcowie** [comment]
This one's easy. I'll add a setting `result_title` (defaulting to 'TODO Results') and append a number to differentiate between existing results pages (TODO Results 1, TODO Results 2 etc.). User can override the title if they want.

**Comment by kgrossjo** [comment]
I wonder why there is the suffix?  Is it to support multiple projects?  I think the user can only have one project open per window at a time, so one "TODO Results" per window should be fine, as well?

There must be something I'm not seeing...

**Comment by robcowie** [comment]
I didn't like the idea of destroying an existing TODO list with a new one. The user may have edited it for example. However, I think I'm probably imagining scenarios that don't really exist. It would certainly be simpler to assume only one TODO list per window.

**Comment by kgrossjo** [comment]
What would happen if the user saved the to do list?  I think that might change the tab title.  And then the next to do command would automatically create a new tab, if the implementation looks at the name...

**Comment by robcowie** [comment]
I'm undecided on what should happen in that case:

a) Don't overwrite the saved view, instead create a new view
b) Replace the contents of the saved view and set is_dirty = True

Both are fairly trivial to implement. Your thoughts are appreciated.

**Comment by kgrossjo** [comment]
I proposed this as a solution for the user to allow editing a to do list without these edits getting clobbered by another invocation of "compute to do items".

So:
- User computes list of to do items
- User starts editing the to do list buffer
- User hits Save and gives that list a new name
- The tab gets renamed
- User computes another list of to do items
- This creates a new tab

And:
- User computes to do list
- User starts editing the to do list buffer
- User computes to do items again without saving the buffer first
- The edits get clobbered

I'm not sure whether this is a good idea.  Just wanted to clarify what I was thinking.

**Comment by robcowie** [comment]
I agree not clobbering user edits in a results view is a good idea. So;
- If no results view exists, create one (with user-definable title)
- If one _does_ exist and it is a scratch buffer (i.e. it has not been saved), overwrite it
- If one does exist _and_ it has been saved, create a new view

Good for you?

**Comment by kgrossjo** [comment]
Purr-fect!
