### ISSUE TITLE
Too slow on big projects?

### ISSUE THREAD

**Issue by ahmedelgabri** [robcowie/SublimeTODO#72]
I'm working on a huge project with 20k+ files & I couldn't find anyway to specify a path or something to search files only inside this path. So each time I want to search for my TODOs I have to wait for 30secs or so till SublimeTODO scans through all the 20k+ files.

Is there is anyway to optimize this? or even use a different package cause it seems that this project is not maintained anymore.

I'm using ST3 on a Mac if this is useful.

**Comment by halcarleton** [comment]
https://github.com/robcowie/SublimeTODO#excluding-files-and-folders

You can exclude paths that you don't want to search easily with the `folder_exclude_patterns` setting. But if you mean on a case by case basis I don't think there's any easy way to do this.

**Comment by ahmedelgabri** [comment]
Ok, can I add this inside a `project.sublime-project` or it needs to be in my main preferences?

**Comment by halcarleton** [comment]
you can include it in your `.sublime-project` file. You will need to put it inside a "settings" object though.

example:

```
{
    "folders":
    [
        {
            "path": "/myproject"
        }
    ],
    "settings":
    {
        "todo":
        {
            "file_exclude_patterns":
            [
                "exclude_me"
            ]
        }
    }
}
```

**Comment by ahmedelgabri** [comment]
Thanks @halleycarleton I'll use this for now but although I prefer something like "search in specific folders" cause with these settings I need to add something like 8 - 10 folders by hand.
