### ISSUE TITLE
No results given with default regex pattern

### ISSUE THREAD

**Issue by thiagodebastos** [robcowie/SublimeTODO#76]
I'm very new with regex and I cannot understand why the default regex pattern isn't working here. Am I making a simple error? I've spent quite some time firguring this out but am really pressed with work at the moment. If this is not a bug, I will go ahead and seek an answer in StackExchange or something. Thanks!

_**Version:** 3071 Dev_
_**Console:** no errors_

---
#### My code:

``` jade
// TODO block header
.hero
    //- TODO fix work assets path
    img
    img.protein(src="/assets/portfolio-assets/examplesite/img/image.png", alt="Product Image")
.header
    h1.project-name
    h3.sub-heading
        // @TODO (5) [convert to mixin]
        include /_includes/portfolio/meta
//- TODO block overview
.overview
    h2.section-header Summary.
    .section-content
        .summary
            p

        .snl-logo
            //- TODO import portfolio assets
```

None of these are being found. I tried playing around on [regex101.com](https://regex101.com/) but just can't seem to get it. I will have to take the time to learn this when I can, hopefully you guys have a quick fix :)

**Comment by GhostLyrics** [comment]
I think it should be

```
TODO:
```

With a colon.

**Comment by thiagodebastos** [comment]
... And this is why I should ask first. Thank you so much, just saved me a headache, it's awalys the simplest answer!
