### ISSUE TITLE
Avoid duplicate tabs

### ISSUE THREAD

**Issue by kgrossjo** [robcowie/SublimeTODO#8]
When I invoke "show todos" twice in a row, I get two tabs with the to do items in them.  I think the second invocation should update the first tab, instead.

Otherwise, if a long time passes between the two invocations of "show todos", then it becomes hard to understand which of the two lists is the more current one.

**Comment by kgrossjo** [comment]
Maybe it becomes easier to do this after doing #7.

**Comment by robcowie** [comment]
Agreed

**Comment by robcowie** [comment]
See f575652

**Comment by kgrossjo** [comment]
Thank you, sir.
